# Generated by Django 3.2.23 on 2024-01-02 09:03

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Utensil',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('recipe', models.CharField(default='default', max_length=100)),
                ('url', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('featured_image_a', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('featured_image_b', models.URLField(blank=True, null=True)),
                ('excerpt', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'DRAFT'), (1, 'Published')], default=0)),
                ('prep_time', models.PositiveIntegerField(blank=True, help_text='Preparation time in minutes', null=True)),
                ('user_vote', models.PositiveSmallIntegerField(choices=[(0, 'Not Voted Yet'), (1, 'Upvote'), (2, 'Downvote')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('ingredients', models.ManyToManyField(blank=True, to='pp4app.Ingredient')),
                ('utensils', models.ManyToManyField(blank=True, to='pp4app.Utensil')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved', models.BooleanField(default=False)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_review', to='pp4app.review')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
