# Generated by Django 3.2.23 on 2023-12-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp4app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='ingredients',
            field=models.ManyToManyField(to='pp4app.Ingredient'),
        ),
        migrations.AddField(
            model_name='review',
            name='utensils',
            field=models.ManyToManyField(to='pp4app.Utensil'),
        ),
    ]
