# Generated by Django 3.2.23 on 2023-12-17 10:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pp4app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='image'),
        ),
    ]
