# Generated by Django 3.2.23 on 2023-12-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp4app', '0002_auto_20231206_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='body',
        ),
        migrations.AddField(
            model_name='review',
            name='comments',
            field=models.ManyToManyField(related_name='reviews', to='pp4app.Comment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='pp4app.Ingredient'),
        ),
        migrations.AlterField(
            model_name='review',
            name='utensils',
            field=models.ManyToManyField(blank=True, to='pp4app.Utensil'),
        ),
    ]
