# Generated by Django 3.2.23 on 2024-01-02 13:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pp4app', '0002_alter_review_featured_image_b'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user_vote',
        ),
        migrations.AddField(
            model_name='review',
            name='down_vote',
            field=models.ManyToManyField(blank=True, related_name='news_down_vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='up_vote',
            field=models.ManyToManyField(blank=True, related_name='news_up_vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
