# Generated by Django 3.2.23 on 2024-01-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp4app', '0003_auto_20240102_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuisineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='cuisine_type',
            field=models.ManyToManyField(blank=True, to='pp4app.CuisineType'),
        ),
    ]
