# Generated by Django 3.2.23 on 2023-12-13 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pp4app', '0003_auto_20231212_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='recipe',
        ),
    ]
