# Generated by Django 3.2.23 on 2023-12-17 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pp4app', '0003_alter_review_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='description',
        ),
        migrations.RemoveField(
            model_name='utensil',
            name='description',
        ),
    ]
