# Generated by Django 3.2.23 on 2023-12-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp4app', '0004_auto_20231217_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='recipe',
            new_name='label',
        ),
        migrations.AddField(
            model_name='review',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
