# Generated by Django 3.2.23 on 2023-12-13 00:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pp4app', '0005_remove_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='review_comments', to='pp4app.review'),
            preserve_default=False,
        ),
    ]
