# Generated by Django 3.2.23 on 2023-12-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp4app', '0005_auto_20231218_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='label',
        ),
        migrations.AlterField(
            model_name='review',
            name='ingredients',
            field=models.ManyToManyField(blank=None, to='pp4app.Ingredient'),
        ),
        migrations.AlterField(
            model_name='review',
            name='utensils',
            field=models.ManyToManyField(blank=None, to='pp4app.Utensil'),
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
