# Generated by Django 3.2.23 on 2023-12-19 14:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp4app', '0006_auto_20231219_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='review',
            name='ingredients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.RemoveField(
            model_name='review',
            name='utensils',
        ),
        migrations.AddField(
            model_name='review',
            name='utensils',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
