# Generated by Django 3.2.23 on 2023-12-19 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pp4app', '0008_auto_20231219_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comments',
        ),
    ]
