# Generated by Django 3.2.23 on 2023-12-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp4app', '0009_remove_review_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='review',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='pp4app.Ingredient'),
        ),
        migrations.RemoveField(
            model_name='review',
            name='utensils',
        ),
        migrations.AddField(
            model_name='review',
            name='utensils',
            field=models.ManyToManyField(blank=True, to='pp4app.Utensil'),
        ),
    ]
