# Generated by Django 3.2.23 on 2023-12-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp4app', '0010_auto_20231224_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='utensil',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
