# Generated by Django 3.2.23 on 2023-12-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pp4app', '0011_auto_20231224_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='recipe',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='prep_time',
            field=models.IntegerField(blank=True, help_text='Preparation time in minutes', null=True),
        ),
    ]