# Generated by Django 3.2.23 on 2023-12-30 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pp4app', '0012_auto_20231229_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='review_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='review_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
